using libmalino;
using System;
using System.IO;

namespace testOS;

public class Shell {
    public static void Start() {
        while (true) {
            Console.Write("\x1b[91m" + Directory.GetCurrentDirectory() + " # \x1b[0m");

			string[] input = malinoIO.UserLine().Trim().Split(' ');

            switch (input[0]) {
                case "help":
                    Console.WriteLine(
                        "testOS v" + MalinoAutoGenerated.OSVersion + "\n" +
                        "Command list:\n\n" +

                        "help - Shows this info\n" +
                        "clear - As its name suggests, clears the screen\n" +
                        "echo - Echoes the arguments you give the command\n" +
                        "reboot - Reboots the computer\n" +
                        "shutdown - Shuts down the computer\n" +
                        "pwd - Prints the working directory\n" + 
                        "about - Displays info about testOS");
                    break;
                case "clear":
                    malinoIO.ClearScreen();
                    break;
                case "pwd":
                    Console.WriteLine("Working directory: " + Directory.GetCurrentDirectory());
                    break;
                case "echo":
                    for (int i = 1; i < input.Length; i++) {
                        Console.Write(input[i] + " ");
                    }
                    Console.WriteLine();
                    break;
                case "reboot":
                    malino.RebootComputer();
                    break;
                case "shutdown":
                    malino.ShutdownComputer();
                    break;
                case "about":
                    Console.WriteLine(
                        "testOS v" + MalinoAutoGenerated.OSVersion + "\n" +
                        "Copyright (c) 2024 Mobren\n" +
                        "MIT License\n\n" +
                        
                        "testOS is a simple operating system in C# to try out malino");
                    break;
                case "":
                    break;
                default:
                    Console.WriteLine(input[0] + ": command not found");
                    break;
            }
        }
    }
}